# Generated by Django 4.2 on 2023-04-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default1.jpg', upload_to='profile_pics'),
        ),
    ]
